name: trackio
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Motor oficial de localización del SDK de Flutter para multiidioma (ca, es, en)
  flutter_localizations:
    sdk: flutter
  intl:

  cupertino_icons:
  maplibre_gl:
  latlong2:
  isar:
  isar_flutter_libs:
  xml:
  flutter_riverpod:
  fl_chart:
  riverpod_annotation:
  file_picker: ^11.0.2
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  isar_generator:
  build_runner:
  riverpod_generator:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/map/style.json
    - assets/trackio_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/trackio_icon.png"
